on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:

  crate_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Login to Crates
      run: cargo login ${{secrets.CRATESIO_API_KEY}}
    - name: Publish Version
      run: cargo publish
      continue-on-error: true


  build_binaries:
    strategy:
      matrix:
        job:
          - { os: macos-latest,   target: x86_64-apple-darwin,         use-cross: false }
          - { os: windows-latest, target: x86_64-pc-windows-msvc,      use-cross: false }
          - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu,    use-cross: false }
    
    runs-on: ${{ matrix.job.os }}
    name: Build ${{ matrix.job.target }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true      
      
      - name: Building to release
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --target ${{matrix.job.target}} --release --all-features --verbose 
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: roll-${{matrix.job.target}}
          path: |
            target/${{matrix.job.target}}/release/roll*
            !target/${{matrix.job.target}}/release/roll.d  
  release:
    env:
      RELEASE_NAME: roll-${{matrix.target}}

    strategy:
      matrix:
        targets: [x86_64-apple-darwin,x86_64-pc-windows-msvc,x86_64-unknown-linux-gnu]

    needs: build_binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts to CWD
        uses: actions/download-artifact@v2

      - name: Package Binaries
        run: zip --junk-paths ${{env.RELEASE_NAME}} ./roll-${{matrix.target}}/* README.md
      # - name: PS Package
      #   if: startsWith(matrix.os,'windows')
      #   run: |
      #     Compress-Archive -Path README -Path target\${{matrix.job.target}}\release\roll.exe -DestinationPath ${{env.RELEASE_NAME}}.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{env.RELEASE_NAME}}.zip
          asset_name: ${{env.RELEASE_NAME}}.zip
          asset_content_type: application/zip
