on: [push, pull_request]
name: Continuous Integration

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --all-features --verbose
    - name: Run tests
      run: cargo test --verbose