name: Publish Crate

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --all-features --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish Version
      run: cargo publish {{secrets.CRATESIO_API_KEY}}