# .github/workflows/release.yml

on:
  release:
    types: [created]
  push:
    branches: [ devel ]
  workflow_dispatch:

jobs:
  
  release:  
    strategy:
      matrix:
        job:
          - { os: macos-latest,   target: x86_64-apple-darwin,         use-cross: false }
          - { os: windows-latest, target: x86_64-pc-windows-msvc,      use-cross: false }
          - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu,    use-cross: false }
    
    runs-on: ${{ matrix.job.os }}
    
    name: release ${{ matrix.job.target }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true      
      
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --target ${{matrix.job.target}} --release
      
      - name: Package # This would actually build your project, using zip for an example artifact
        run: |
          RELEASE_NAME=roll-${{matrix.job.target}}
          zip --junk-paths $RELEASE_NAME target/${{matrix.job.target}}/roll README.md
        
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            $RELEASE_NAME.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
